.travis.yml, composer.json, src/Deserializers/EntityDeserializer.php, src/Serializers/FingerprintSerializer.php, tests/unit/Deserializers/EntityDeserializerTest.php, tests/unit/Serializers/FingerprintSerializerTest.php
Requires https://github.com/wmde/WikibaseDataModel/pull/272
=> Add requirements for language fall backs.

src/Serializers/ItemSerializer.php
The parameter can't be an `Entity`, it's guaranteed to be an `Item`.
=> Fix wrong type hint in ItemSerializer

src/Deserializers/ItemDeserializer.php, tests/integration/EntitySerializationRoundtripTest.php, tests/unit/Deserializers/EntityDeserializerTest.php, tests/unit/Deserializers/ItemDeserializerTest.php, tests/unit/Deserializers/PropertyDeserializerTest.php, tests/unit/SerializerFactoryTest.php, tests/unit/Serializers/FingerprintSerializerTest.php, tests/unit/Serializers/ItemSerializerTest.php, tests/unit/Serializers/PropertySerializerTest.php
1. Favor constructor calls over static methods.
2. Favor using constructor parameters over calling `setId` (see https://github.com/wmde/WikibaseDataModel/pull/348).
=> Favor constructors over newEmpty

src/DeserializerFactory.php, src/Deserializers/EntityDeserializer.php, src/SerializerFactory.php, src/Serializers/ItemSerializer.php, src/Serializers/PropertySerializer.php, tests/unit/DeserializerFactoryTest.php, tests/unit/Deserializers/EntityDeserializerTest.php, tests/unit/Deserializers/ItemDeserializerTest.php, tests/unit/Deserializers/PropertyDeserializerTest.php, tests/unit/SerializerFactoryTest.php, tests/unit/Serializers/FingerprintSerializerTest.php, tests/unit/Serializers/ItemSerializerTest.php, tests/unit/Serializers/PropertySerializerTest.php
This replaces the `claims` key with a `statements` key in the serialization which is a breaking change. We might consider to use `claims` in future as well for b/c but imo it would be cleaner to change the serialization key as well when we discard the whole concept of claims.
See #82 and #120
=> Use StatementListSerializer where appropriate

README.md, RELEASE-NOTES.md
This makes the README file look more like the one of Wikibase DataModel.
=> Move release notes into their own file and reorder some sections

src/Deserializers/FingerprintDeserializer.php, tests/unit/Deserializers/DeserializerBaseTest.php, tests/unit/Deserializers/FingerprintDeserializerTest.php
This fixes an older issue already present before #122 and also reverts parts of #122, see my comments there.
=> Add missing exceptions to FingerprintDeserializer

src/Deserializers/ClaimsDeserializer.php, src/Deserializers/EntityIdDeserializer.php, src/Deserializers/FingerprintDeserializer.php, src/Deserializers/ReferenceDeserializer.php, src/Deserializers/ReferenceListDeserializer.php, src/Deserializers/SiteLinkDeserializer.php, src/Deserializers/SnakListDeserializer.php, src/Serializers/ReferenceSerializer.php, tests/integration/ClaimsSerializationRoundtripTest.php, tests/integration/ReferenceSerializationRoundtripTest.php, tests/integration/ReferencesSerializationRoundtripTest.php, tests/integration/SiteLinkSerializationRoundtripTest.php, tests/integration/SnaksSerializationRoundtripTest.php, tests/unit/Deserializers/ClaimDeserializerTest.php, tests/unit/Deserializers/ClaimsDeserializerTest.php, tests/unit/Deserializers/DeserializerBaseTest.php, tests/unit/Deserializers/EntityDeserializerTest.php, tests/unit/Deserializers/FingerprintDeserializerTest.php, tests/unit/Deserializers/PropertyDeserializerTest.php, tests/unit/Deserializers/ReferenceListDeserializerTest.php, tests/unit/Deserializers/SnakListDeserializerTest.php, tests/unit/Deserializers/StatementListDeserializerTest.php, tests/unit/Serializers/ReferenceListSerializerTest.php, tests/unit/Serializers/ReferenceSerializerTest.php, tests/unit/Serializers/SiteLinkSerializerTest.php, tests/unit/Serializers/SnakSerializerTest.php
* Newlines.
* Unused imports.
* Consistent wording of exception messages.
* Providers can't return anything but an array of arrays, even "invalid" providers must do that.
=> Fix minor style and formatting issues

src/Deserializers/ClaimDeserializer.php, src/Deserializers/FingerprintDeserializer.php, src/Deserializers/SnakDeserializer.php, src/Serializers/ClaimsSerializer.php, src/Serializers/FingerprintSerializer.php, src/Serializers/ItemSerializer.php, src/Serializers/ReferenceListSerializer.php, src/Serializers/ReferenceSerializer.php, src/Serializers/SnakSerializer.php, src/Serializers/SnaksSerializer.php, src/Serializers/StatementListSerializer.php, src/Serializers/TypedSnakSerializer.php
None of these classes does have subclasses, therefor "protected" is meaningless and identical to "private".
=> Private by default

src/Serializers/ClaimSerializer.php, src/Serializers/ClaimsSerializer.php, src/Serializers/ItemSerializer.php, src/Serializers/PropertySerializer.php, src/Serializers/ReferenceListSerializer.php, src/Serializers/ReferenceSerializer.php, src/Serializers/SiteLinkSerializer.php, src/Serializers/SnakSerializer.php, src/Serializers/SnaksSerializer.php, src/Serializers/StatementListSerializer.php, src/Serializers/TypedSnakSerializer.php
All these parameters must be of this type, otherwise the call throws an exception. It's guaranteed to do so. This is part of the public interface. So this has nothing to do with "package private" or something.
=> More specific type hints in Serializers

src/Deserializers/ClaimDeserializer.php, src/Deserializers/ClaimsDeserializer.php, src/Deserializers/EntityDeserializer.php, src/Deserializers/EntityIdDeserializer.php, src/Deserializers/FingerprintDeserializer.php, src/Deserializers/ReferenceDeserializer.php, src/Deserializers/ReferenceListDeserializer.php, src/Deserializers/SiteLinkDeserializer.php, src/Deserializers/SnakDeserializer.php, src/Deserializers/SnakListDeserializer.php, src/Deserializers/StatementListDeserializer.php
All these parameters and return types must be of this type, otherwise the call throws an exception. It's guaranteed to do so. This is part of the public interface. So this has nothing to do with "package private" or something.
=> More specific type hints in Deserializers

src/DeserializerFactory.php, src/Deserializers/SnakDeserializer.php, src/SerializerFactory.php, src/Serializers/FingerprintSerializer.php, src/Serializers/PropertySerializer.php, tests/unit/Serializers/FingerprintSerializerTest.php
This fixes two issues mentioned in #137:
* Make methods private if not used from outside the class.
* Rename $entity to $property.
Also:
* Optimize imports.
=> Make FingerprintSerializer methods private

RELEASE-NOTES.md, src/SerializerFactory.php, src/Serializers/SnakSerializer.php, src/Serializers/StatementSerializer.php, tests/unit/Serializers/SnakSerializerTest.php
In the current Wikibase Lib serializers there is
an option to serialize snaks without a hash.
This is due to the fact that the hashes are not all
that usefull in the API output.
To avoid adding these hashes to the serialization
this option is needed
=> Add Serialization option for snak hashes

src/SerializerFactory.php, src/Serializers/ClaimsSerializer.php, tests/unit/SerializerFactoryTest.php, tests/unit/Serializers/AliasGroupListSerializerTest.php, tests/unit/Serializers/ClaimsSerializerTest.php
This is a non-breaking change that should have zero effect to the public interface. The idea is to reduce the occurrences of the word "claim" in this component to a minimum.
=> Reduce mentions of Claim(s) without breaking anything

README.md, RELEASE-NOTES.md, composer.json, mediawiki.php, src/DeserializerFactory.php, src/Deserializers/EntityIdDeserializer.php, tests/integration/ClaimsSerializationRoundtripTest.php, tests/integration/EntityDeserializationCompatibilityTest.php, tests/integration/EntitySerializationRoundtripTest.php, tests/integration/ReferenceSerializationRoundtripTest.php, tests/integration/ReferencesSerializationRoundtripTest.php, tests/integration/SiteLinkSerializationRoundtripTest.php, tests/integration/SnakListSerializationRoundtripTest.php, tests/integration/SnakSerializationRoundtripTest.php, tests/integration/StatementSerializationRoundtripTest.php, tests/unit/DeserializerFactoryTest.php, tests/unit/Deserializers/EntityIdDeserializerTest.php
Reverts wmde/WikibaseDataModelSerialization#166
This was a breaking change and should not get released as a 1.9 but a 2.0. We must do a 1.9.1 release which fixes this issue and then release the changes again as 2.0.
=> Revert "Drop dependency on Wikibase DataModel Services"

tests/integration/EntitySerializationRoundtripTest.php, tests/unit/Deserializers/ItemDeserializerTest.php, tests/unit/Serializers/ItemSerializerTest.php
This also avoids calling a deprecated method.
=> Favor addNewSiteLink() over addSiteLink( new SiteLink() )

tests/bootstrap.php
This fixes a series of minor issues:
* The var contains a `ClassLoader` object. I find it helpful when the name reflects that.
* Not sure what the var contains when the file is not included because of the `_once`. Better be strict and use `require`.
* `require` is not a function, MediaWiki's and Wikibase' PHPCS complain about the brackets.
* `unset` in the end.
Most of this is already done in most bootstrap.php files we have.
=> Cleaner autoload code in test bootstrap

src/Deserializers/StatementDeserializer.php
This is required in some serializers, but not here.
=> Remove not needed "by ref" ampersands

composer.json
* This component is compatible with Common 0.3.x. [The breaking changes between Common 0.2.x and 0.3.x](https://github.com/DataValues/Common/compare/0.2.3...0.3.0) are not used here.
Also see:
* https://github.com/DataValues/Geo/pull/58
* https://github.com/DataValues/Number/pull/53
* https://github.com/wmde/WikibaseInternalSerialization/pull/90
=> Compatible with DataValues Common 0.3.0

RELEASE-NOTES.md, src/DeserializerFactory.php, src/SerializerFactory.php, tests/unit/DeserializerFactoryTest.php, tests/unit/SerializerFactoryTest.php
These methods need to be accessible from outside because we want to create
a Dispatchable(De)Serializer in a place where we know all available entity
types and have access to their serializers. That way we can avoid
unneccessarily nesting dispatching serializers and have a clear place in
our code where that dispatching happends.
Bug: [T126932](https://phabricator.wikimedia.org/T126932)
=> Add public item/property (de)serializer factory methods

tests/unit/Deserializers/PropertyDeserializerTest.php, tests/unit/Serializers/ItemSerializerTest.php, tests/unit/Serializers/PropertySerializerTest.php
The fact that a property type can be empty is an edge case that should be avoided when the code doesn't really depend on it.
=> Avoid using empty property type in Property::newFromType

RELEASE-NOTES.md, composer.json, mediawiki-extension.json
This is so cool. We worked hard on the DataModel 5.0 release, discussing what should be in there, and it took us some time. Look how this turns out now. Stuff is still compatible with both versions! I'm happy. :-)
As with https://github.com/wmde/WikibaseDataModelServices/pull/113, please have a look at the open pull requests before tagging a release.
Would be really, really cool to release this today.
=> Release 2.1.0

src/DeserializerFactory.php, src/Deserializers/AliasGroupListDeserializer.php, src/Deserializers/SnakDeserializer.php, src/Deserializers/StatementDeserializer.php, src/Deserializers/TermListDeserializer.php, tests/unit/DeserializerFactoryTest.php
This also adds a missing `@throws` I found while splitting these lines.
=> Split function headers longer than 100 characters

README.md, composer.json, phpunit.xml.dist, tests/integration/EntityDeserializationCompatibilityTest.php
This test is not so slow that it should be an issue. It's less than a second. Not having this executed by default when you type "phpunit" is a bigger issue, in my opinion.
I'm also removing all value types that do not appear in the data directory.
=> Remove slow tag from EntityDeserializationCompatibilityTest

RELEASE-NOTES.md, composer.json, mediawiki-extension.json, src/DeserializerFactory.php, src/SerializerFactory.php, tests/integration/EntityDeserializationCompatibilityTest.php
Pinging @Benestar.
Note that the EntityDeserializationCompatibilityTest is in a "slow" group and excluded by default. Fixed in #196.
[Bug: T128468](https://phabricator.wikimedia.org/T128468)
=> Release 2.2.0

.travis.yml
* PHP 5.6 was not tested.
* ~4.0 is misleading because this is not compatible with versions before 4.2 any more.
* Testing with 5.0@dev is obsolete with 6.0.
Same in:
* https://github.com/wmde/WikibaseDataModelServices/pull/140
* https://github.com/wmde/WikibaseInternalSerialization/pull/108
=> Update DataModel version matrix in .travis.yml

composer.json
Note that this is in the `require-dev` section and not critical for anything. The only detail this component cares about is if the QuantityValue class exists or not, which is the case in all versions. This is mostly for consistency and does not need a release.
=> Update DataValues Number to 0.8.0

src/Deserializers/ItemDeserializer.php, src/Deserializers/PropertyDeserializer.php, src/Deserializers/ReferenceListDeserializer.php, src/Deserializers/SnakDeserializer.php, src/Deserializers/SnakListDeserializer.php, src/Deserializers/StatementDeserializer.php, src/Deserializers/StatementListDeserializer.php, src/Deserializers/TermListDeserializer.php
This patch fixes a lot of type safety warnings in this code without touching any interface or exposing package private knowledge.
This is an addition to #198. It does not make #198 obsolete.
=> Fix all "incompatible type" warnings

RELEASE-NOTES.md, composer.json, mediawiki-extension.json
I consider the two removed `DeserializerBaseTest` and `SerializerBaseTest` base classes an implementation detail and not a braking change.
=> Release 2.3.0

src/Deserializers/AliasGroupListDeserializer.php, src/Deserializers/SnakListDeserializer.php, src/Deserializers/StatementListDeserializer.php, src/Deserializers/TermListDeserializer.php
This patch does have two effects:
* It merges duplicate loops that looped the exact same arrays twice.
* This allows to avoid a few duplicate condition checks, e.g. duplicate `is_string`.
This is a direct follow up for #205.
[Bug: T157959](https://phabricator.wikimedia.org/T157959)
=> Merge duplicate array loops

src/Deserializers/SnakListDeserializer.php
This is quite critical. I believe `addElement` should be considered an implementation detail, because this is the method from the underlying abstract `HashArray` base class. The `SnakList` class does have a dedicated `addSnak`, and only this should be used to add snaks.
This is the only user of this method. This block us from removing the abstract base class, see https://github.com/wmde/WikibaseDataModel/pull/702.
=> Do not use SnakList::addElement

composer.json, tests/integration/EntityDeserializationCompatibilityTest.php
This was still using the deprecated alias of the GlobeCoordinateValue class. How did we missed that?
[Bug: T165123](https://phabricator.wikimedia.org/T165123)
=> Declare compatibility with data-values/geo 2.0

.travis.yml, src/Deserializers/EntityIdDeserializer.php, src/Deserializers/ItemDeserializer.php, src/Deserializers/PropertyDeserializer.php, src/Deserializers/ReferenceDeserializer.php, src/Deserializers/ReferenceListDeserializer.php, src/Deserializers/SiteLinkDeserializer.php, src/Deserializers/SnakDeserializer.php, src/Deserializers/SnakListDeserializer.php, src/Deserializers/StatementListDeserializer.php, src/Deserializers/TermListDeserializer.php, src/Serializers/PropertySerializer.php, src/Serializers/ReferenceListSerializer.php, src/Serializers/ReferenceSerializer.php, src/Serializers/StatementSerializer.php, src/Serializers/TypedSnakSerializer.php, tests/integration/ReferencesSerializationRoundtripTest.php, tests/unit/Deserializers/ReferenceListDeserializerTest.php
This patch removes auto-generated PHPDoc blocks that contain nothing but a sequence of `@param` lines that *literally* repeat what the function header below contains. These blocks add zero additional information, but clutter the code and need to be maintained. This patch does not touch PHPDoc blocks when one of the `@param` lines contains an actual comment behind the variable name, or when one of the types is not a class name.
See https://gerrit.wikimedia.org/r/360814 for the same patch in the Wikibase.git code base.
=> Remove auto-generated @param-only PHPDoc blocks that add zero information

tests/integration/EntitySerializationRoundtripTest.php
This is a pretty straight refactoring of this test. The only actual change is that this is not testing the `newEntity…` methods any more, but the two separate `newItem…` and `newProperty…`. I believe this is ok for a test that claims to test roundtrips.
There is one aspect that should be tested somewhere: an Item serialization should not be deserialized by the Property deserializer, and the other way around. But this is not the job of this test. It is not even build to test this, and would only catch such an error by random chance.
This is split from #220.
=> Rewrite EntitySerializationRoundtripTest

RELEASE-NOTES.md, src/SerializerFactory.php, tests/unit/SerializerFactoryTest.php
Suppressing snak hashes was initially added as a single option in 656398540f, but then split up into three options in 679774d120, since the previous lib serializer included qualifier hashes but not main snak or reference hashes, and the goal was to migrate from that serializer to this one with absolutely no change in the output. Now that this migration is done, we can merge the three options into one again, since it’s hardly useful to have snak hashes for some snaks but not others: either include all hashes, or omit all of them.
This is implemented as an extra constant, which is the bitwise union of the three existing ones, for backwards compatibility. With the next major release, the three old options should be removed and the single option made functional instead (with a single method …
=> Merge options to use snak hashes into one

RELEASE-NOTES.md, composer.json, phpcs.xml, tests/unit/Deserializers/StatementDeserializerTest.php
Note that #222 should be in this release!
I used the opportunity to lower the line length a little bit, to a limit where I only had to touch two lines in a single file. I ended touching a few more lines because I decided to rename some variables (I found $snakDeserializerMock and $snaksDeserializerMock especially confusing – the only difference was an "s" in the middle of the variable name).
=> Release 2.6.0

README.md, RELEASE-NOTES.md, src/DeserializerFactory.php, src/SerializerFactory.php
This should be done before #220.
[Bug: T160436](https://phabricator.wikimedia.org/T160436)
=> Improve documentation of confusing newEntity(De)Serializer methods

tests/unit/Serializers/ItemSerializerTest.php, tests/unit/Serializers/PropertySerializerTest.php
We are planning a release where setId does not accept integers any more. Code like this here should just not exist any more.
=> Stop using numeric entity IDs

src/Deserializers/AliasGroupListDeserializer.php, src/Deserializers/TermListDeserializer.php, tests/unit/Deserializers/AliasGroupListDeserializerTest.php, tests/unit/Deserializers/TermListDeserializerTest.php
This is a bug because both the Term class as well as the AliasGroup class happily accept language codes that only consist of digits, e.g. `new Term( '8', 'Eight' )`. The problem is that PHP forcefully converts array keys to integers if they look like an integer, even if provided as a string. There is nothing that can be done to avoid this magic behavior.
This patch solves the problem by replacing `!==` with strcmp, which includes a type conversion back to string.
We found this while working on https://gerrit.wikimedia.org/r/378889.
This is not critical in production because language codes that are only made of numbers don't exist. But this is a bug no matter what.
=> Fix Alias/TermDeserializers failing on numeric array keys

src/DeserializerFactory.php, src/Deserializers/SnakDeserializer.php, tests/unit/Deserializers/SnakDeserializerTest.php
* The fact that an UnDeserializableValue was constructed just *assuming* the "type" and "value" array elements are there was a bug. This code path is executed when the DataValueDeserializer fails, which includes the situation when one or both array elements are just missing.
* I'm also removing the awkward EntityIdDeserializer injection. This code path can not accept anything but PropertyIds. There was even a check for this. Why do we need to call an overly complex generic "EntityId" deserializer, if we know already what entity type we expect? Note this is not a breaking change because all this is declared "package-private".
* Also remove the unused "composer cs" command.
[Bug: T178651](https://phabricator.wikimedia.org/T178651)
=> Fix SnakDeserializer causing "Undefined index" errors

RELEASE-NOTES.md, composer.json, tests/integration/SnakSerializationRoundtripTest.php
This is the next step in updating the dependency tree that started here:
* https://github.com/wmde/Serialization/pull/21
* https://github.com/DataValues/Serialization/pull/35
I had to update one roundtrip test to make it compatible with both versions. Before, the error message was empty, which was a bug. I think this is worth it. The error message is not part of the actual value, and should not be considered in a roundtrip test.
Note there are quite a lot of pull requests open here, and (as always) it would be awesome if we yould include at least some of them into this release. I suggest these candidates:
* #241 fixes an actual bug that causes logspam.
* #240 is not critical for production but a bugfix anyway.
* #239 is also a bugfix. Callers already asume the returned objects are …
=> Make compatible with serialization/serialization 4.x

src/DeserializerFactory.php, src/SerializerFactory.php
To know this is critical for external callers as well as internally. Look how the newEntityDeserializer method uses the return values from newItemDeserializer and newPropertyDeserializer: in a DispatchingDeserializer, which requires the values to be of type DispatchableDeserializer. Same is true for usages outside of this component. So this information is already public, just not documented properly.
=> Document public getters to return Dispatchable(De)serializers

.phpcs.xml, composer.json
=> Replace wikibase-codesniffer with mediawiki-codesniffer
